version: '3.8'
services:
  client:
    image: 200636470037.dkr.ecr.us-west-1.amazonaws.com/gog-dapp-test-frontend:latest
    build: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    #build:
      #dockerfile: Dockerfile
      #context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
