version: '3.8'
services:
  client:
    image: 'WhaleConnectedVenturesFrontend:latest'
    build: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    #build:
      #dockerfile: Dockerfile
      #context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:80"
